### ISSUE TITLE
Dependency Ordering

### ISSUE THREAD

**Issue by TheKevJames** [TheKevJames/ifttt#4]
If would be great to be able to do:

```yaml
- name: enable thing
  if: value
  ...

- name: change thing
  after: "enable thing"
```

In the case where `change thing` can only be run after `enable thing` completes.
