### ISSUE TITLE
ElasticSearch Watcher

### ISSUE THREAD

**Issue by TheKevJames** [TheKevJames/ifttt#6]
Use case:

```yaml
- name: alert on unprocessed jobs
  watch:
    source: elasticsearch
    connection_string: ...
    index: es-index
    query: {"filtered": {"filter": {"range": {"created": {"gte": "now-10m"}}}}}
  if: !curr['hits']['total']
  then:
    - send-slack-notif -t "no jobs processed in last ten minutes!"
```
