### ISSUE TITLE
Interpolate Math

### ISSUE THREAD

**Issue by TheKevJames** [TheKevJames/ifttt#9]
To reduce some complexity in action scripts, it'd be great if we could interpolate math. For example:

```yaml
- name: ensure each user has seven nodes
  watch: ...
  then:
    - set-node-count {value * 7}
```
